source 'https://rubygems.org'

gem "ocean-rails"

gem "rails"
gem "pg"
gem "foreigner"
gem "jbuilder"

gem "spring", group: :development

group :test, :development do
  gem "sqlite3"
  gem "memory_test_fix"
  gem "rspec-rails"
  gem "simplecov", require: false
  gem "factory_girl_rails", "~> 4.0"
  gem "immigrant"
  gem "annotate", ">=2.5.0"
end

gem "protected_attributes"
